### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Noah670** [Soldy/AMA#1]
How are you doing?

**Comment by Soldy** [comment]
Fine like always. u ?

**Comment by Noah670** [comment]
I'm doing good thanks

**Comment by Soldy** [comment]
What are you working on ?

**Comment by Noah670** [comment]
> What are you working on ?

Right now I'm working on a react project

**Comment by Soldy** [comment]
Everyone working on react at the moment.

**Comment by Noah670** [comment]
That's true

**Comment by Soldy** [comment]
Do you wan to try something new ?

**Comment by Noah670** [comment]
What do you mean?

**Comment by Soldy** [comment]
Check this :) https://github.com/Soldy/trollhand

**Comment by Noah670** [comment]
Very cool :)

**Comment by Soldy** [comment]
I hope you enjoy it :)
